local builtin = require("telescope.builtin")
-- This will load the `lua/wiklund.lua` or `lua/wiklund/init.lua` file

-- PERSONAL
vim.keymap.set("n", "J", "5j", {})
vim.keymap.set("n", "K", "5k", {})
vim.keymap.set("n", "<C-p>", builtin.git_files, {})
vim.keymap.set("n", "<C-l>", ":Neogit <CR>")
vim.keymap.set("n", "<leader>e", vim.diagnostic.open_float, { desc = "Open floating diagnostic message" })
vim.keymap.set("n", "H", vim.lsp.buf.hover, { desc = "Hover documentation" })
vim.keymap.set("n", "-", "<CMD>Ex<CR>", { desc = "Open parent directory" })

-- DAP
-- vim.keymap.set("n", "<F5>", function()
-- 	require("dap").continue()
-- end)
-- vim.keymap.set("n", "<F10>", function()
-- 	require("dap").step_over()
-- end)
-- vim.keymap.set("n", "<F11>", function()
-- 	require("dap").step_into()
-- end)
-- vim.keymap.set("n", "<F12>", function()
-- 	require("dap").step_out()
-- end)
-- vim.keymap.set("n", "<Leader>b", function()
-- 	require("dap").toggle_breakpoint()
-- end)
-- vim.keymap.set("n", "<Leader>B", function()
-- 	require("dap").set_breakpoint()
-- end)
-- vim.keymap.set("n", "<Leader>lp", function()
-- 	require("dap").set_breakpoint(nil, nil, vim.fn.input("Log point message: "))
-- end)
-- vim.keymap.set("n", "<Leader>dr", function()
-- 	require("dap").repl.open()
-- end)
-- vim.keymap.set("n", "<Leader>dl", function()
-- 	require("dap").run_last()
-- end)
-- vim.keymap.set({ "n", "v" }, "<Leader>dh", function()
-- 	require("dap.ui.widgets").hover()
-- end)
-- vim.keymap.set({ "n", "v" }, "<Leader>dp", function()
-- 	require("dap.ui.widgets").preview()
-- end)
-- vim.keymap.set("n", "<Leader>df", function()
-- 	local widgets = require("dap.ui.widgets")
-- 	widgets.centered_float(widgets.frames)
-- end)
-- vim.keymap.set("n", "<Leader>ds", function()
-- 	local widgets = require("dap.ui.widgets")
-- 	widgets.centered_float(widgets.scopes)
-- end)
--
-- local dap = require("dap")
-- local dapui = require("dapui")
--
-- -- Basic debugging commands
-- vim.keymap.set("n", "<Leader>db", dap.toggle_breakpoint, { desc = "[D]ebug [B]reakpoint" })
-- vim.keymap.set("n", "<Leader>dc", dap.continue, { desc = "[D]ebug [C]ontinue" })
-- vim.keymap.set("n", "<Leader>di", dap.step_into, { desc = "[D]ebug Step [I]nto" })
-- vim.keymap.set("n", "<Leader>do", dap.step_over, { desc = "[D]ebug Step [O]ver" })
-- vim.keymap.set("n", "<Leader>du", dap.step_out, { desc = "[D]ebug Step [O]ut" })
-- vim.keymap.set("n", "<Leader>dr", dap.repl.open, { desc = "[D]ebug [R]EPL" })
-- vim.keymap.set("n", "<Leader>dq", dap.terminate, { desc = "[D]ebug [Q]uit" })
-- vim.keymap.set("n", "<Leader>dl", dap.run_last, { desc = "[D]ebug [L]ast" })
--
-- -- Conditional breakpoints
-- vim.keymap.set("n", "<Leader>dB", function()
-- 	dap.set_breakpoint(vim.fn.input("Breakpoint condition: "))
-- end, { desc = "[D]ebug [B]reakpoint with Condition" })
--
-- -- View state
-- -- vim.keymap.set("n", "<Leader>dh", dap.hover, { desc = "[D]ebug [H]over" })
-- -- vim.keymap.set("n", "<Leader>dp", dap.preview, { desc = "[D]ebug [P]review" })
--
-- -- DAP UI
-- vim.keymap.set("n", "<Leader>dU", dapui.toggle, { desc = "[D]ebug [U]I Toggle" })
-- vim.keymap.set("n", "<Leader>de", dapui.eval, { desc = "[D]ebug [E]valuate" })
